[package]
name = "pest-deconstruct-derive"
version = "0.2.0"
authors = ["cad97 <cad97@cad97.com>"]
description = "Internal implementation detail of pest-deconstruct"
license = "MIT"

[lib]
name = "derive"
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4"
single = "1.0.0"
itertools = "0.7.8"
